name: solid_principle_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  solid_domain:
    path: packages/solid_domain
  solid_data_api:
    path: packages/solid_data_api
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true