name: solid_principle_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  intl: ^0.17.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get: ^4.6.5
  supercharged: ^2.1.1
  device_preview: ^1.1.0
  fluttertoast: ^8.0.9
  shimmer: ^2.0.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.1
  hive: ^2.2.3
  connectivity_plus: ^2.3.7
  hive_flutter: ^1.1.0
  formz: ^0.4.1
  flutter_spinkit: ^5.1.0

dependency_overrides:
    pull_to_refresh:
      git:
        url: https://github.com/miquelbeltran/flutter_pulltorefresh
        ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/