name: solid_principle_app
description: SOLID is an acronym for the first five object-oriented design (OOD) principles by Robert C. Martin (also known as Uncle Bob).
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  intl: ^0.17.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get: ^4.6.5
  supercharged: ^2.1.1
  device_preview: ^1.1.0
  fluttertoast: ^8.0.9
  shimmer: ^2.0.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.1
  formz: ^0.4.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.5
  url_launcher: ^6.1.6
  flutter_native_splash: ^2.2.9
  flutter_flavorizr: ^2.1.4
  flutter_launcher_icons: ^0.10.0
  flutter_dotenv: ^5.0.2

  solid_data:
    path: packages/solid_data

  solid_domain:
    path: packages/solid_domain

dependency_overrides:
    pull_to_refresh:
      git:
        url: https://github.com/miquelbeltran/flutter_pulltorefresh
        ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/images/common/
    - .env.production
    - .env.development

# For update your flavors
# f pub run flutter_flavorizr -p <processor1>,<processor2>
flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:
  ide: "vscode"

  flavors:
    development:
      app:
        name: "[DEV] Solid App"

      android:
        applicationId: "com.biscuit.solid_principle_app"
      ios:
        bundleId: "com.biscuit.solid_principle_app"
        # buildSettings:
        #   # Development Team is visible in the apple developer portal 
        #   DEVELOPMENT_TEAM: YOURDEVTEAMID 
        #   PROVISIONING_PROFILE_SPECIFIER: "Dev-ProvisioningProfile"

    production:
      app:
        name: "Solid App"

      android:
        applicationId: "com.example.solid_principle_app"
      ios:
        bundleId: "com.example.solid_principle_app"
        # buildSettings:
        #   DEVELOPMENT_TEAM: YOURPRODUCTIONTEAMID
        #   PROVISIONING_PROFILE_SPECIFIER: "Production-ProvisioningProfile"