name: solid_data
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dio: 4.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  hive: ^2.2.3
  connectivity_plus: ^2.3.7
  fluttertoast: ^8.0.9
  hive_flutter: ^1.1.0

  solid_domain:
    path: ../solid_domain
  get_it: ^7.2.0

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  
